export default {
  title: "",
  zoomType: "fill-width",
  width: 1440,
  height: 900,
  whUnit: "px",
  backgroundColor: "#1b1f25",
  backgroundImage: "",
  color: "#fff",
  fontSize: 14,
  fontUnit: "px",
  fontWeight: 400,
  fontFamily: "",
  grideSpace: 10,
};
